DROP TABLE FERIADOS;

DROP TABLE PERMISO_RESOLUCIONES;
DROP TABLE PERMISO_ESTADOS;
DROP TABLE PERMISO_TIPOS;
DROP TABLE PERMISO_MOTIVOS;
DROP TABLE PERMISO_ADJUNTOS;

DROP TABLE USUARIO_PERFILES;
DROP TABLE USUARIO_CARGOS;
DROP TABLE USUARIO_DEPARTAMENTOS;

DROP TABLE PERMISOS;

DROP TABLE USUARIOS;

DROP SEQUENCE SEQ_PERMISOS;

DROP SEQUENCE SEQ_PERMISO_ADJUNTOS;
DROP SEQUENCE SEQ_PERMISO_ESTADOS;
DROP SEQUENCE SEQ_PERMISO_MOTIVOS;
DROP SEQUENCE SEQ_PERMISO_RESOLUCIONES;
DROP SEQUENCE SEQ_PERMISO_TIPOS;

DROP SEQUENCE SEQ_USUARIO_CARGOS;
DROP SEQUENCE SEQ_USUARIO_DEPARTAMENTOS;
DROP SEQUENCE SEQ_USUARIO_PERFILES;

DROP SEQUENCE SEQ_FERIADOS;

COMMIT;