--	CREAR TABLAS	--
CREATE TABLE FERIADOS (
    id_feriado NUMBER (9,0),
    feriado TIMESTAMP,
    descripcion VARCHAR2(255),
    CONSTRAINT FERIADOS_PK PRIMARY KEY (feriado)
);

CREATE TABLE PERMISO_RESOLUCIONES (
    id_resolucion NUMBER (9,0),
    codigo VARCHAR2(255),
    detalle VARCHAR2(255),
    ruta_documento VARCHAR2(255),
    fecha_creacion TIMESTAMP,
    CONSTRAINT RESOLUCION_PK PRIMARY KEY (id_resolucion)
);

CREATE TABLE PERMISO_ADJUNTOS (
    id_adjunto NUMBER (9,0),
    nombre_documento VARCHAR2(100),
    ruta_documento VARCHAR2(255),
    CONSTRAINT ADJUNTO_PK PRIMARY KEY (id_adjunto)
);

CREATE TABLE PERMISO_ESTADOS (
    id_estado NUMBER (9,0),
    estado VARCHAR2(25),
    descripcion VARCHAR2(100),
    CONSTRAINT PERMISO_ESTADO_PK PRIMARY KEY (id_estado)
);
CREATE TABLE PERMISO_TIPOS (
    id_tipo NUMBER (9,0),
    tipo VARCHAR2(25),
    dias NUMBER (38,0),
    descripcion VARCHAR2(100),
    estado_tipo NUMBER (38,0),
    CONSTRAINT PERMISO_TIPO_PK PRIMARY KEY (id_tipo)
);

CREATE TABLE PERMISO_MOTIVOS (
  id_motivo NUMBER (9,0),
  motivo VARCHAR2(255),
  CONSTRAINT PERMISO_MOTIVO_PK PRIMARY KEY (id_motivo)
);

CREATE TABLE USUARIO_PERFILES (
    id_perfil NUMBER (9,0),
    perfil VARCHAR2(25),
    descripcion VARCHAR2(100),
    CONSTRAINT USUARIO_PERFIL_PK PRIMARY KEY (id_perfil)
);

CREATE TABLE USUARIO_CARGOS (
    id_cargo NUMBER (9,0),
    cargo VARCHAR2(100),
    descripcion VARCHAR2(100),
    CONSTRAINT CARGO_PK PRIMARY KEY (id_cargo)
);

CREATE TABLE USUARIO_DEPARTAMENTOS ( 
    id_departamento NUMBER (9,0), 
    departamento VARCHAR2(100),
    descripcion VARCHAR2(300),
    CONSTRAINT DEPARTAMENTO_PK PRIMARY KEY (id_departamento)
);

CREATE TABLE USUARIOS (
  rut NUMBER (9,0),
  dv VARCHAR2(1),
  clave VARCHAR2(255),
  nombres VARCHAR2(100),
  apellido_paterno VARCHAR2(100),
  apellido_materno VARCHAR2(100),
  direccion VARCHAR2(100),
  comuna VARCHAR2(100),
  telefono NUMBER (15,0),
  email VARCHAR2(100),
  dd_legales NUMBER(3,0),
  dd_administrativos NUMBER (3,0),
  fecha_contrato TIMESTAMP,
  perfil NUMBER (9,0),
  cargo NUMBER (9,0),
  departamento NUMBER (9,0),
  CONSTRAINT USUARIO_PK PRIMARY KEY (rut),
  CONSTRAINT USUARIO_FK_PERFIL FOREIGN KEY (perfil) REFERENCES USUARIO_PERFILES (id_perfil),
  CONSTRAINT USUARIO_FK_CARGO FOREIGN KEY (cargo) REFERENCES USUARIO_CARGOS (id_cargo),
  CONSTRAINT USUARIO_FK_DEPARTAMENTO FOREIGN KEY (departamento) REFERENCES USUARIO_DEPARTAMENTOS (id_departamento)
);

CREATE TABLE PERMISOS (
    id_permiso NUMBER (9,0),
    fecha_creacion TIMESTAMP,
    fecha_desde TIMESTAMP,
    fecha_hasta TIMESTAMP,
    dias NUMBER (3,0),
    observacion VARCHAR2(255),
    usuario NUMBER (9,0),
    resolucion NUMBER (9,0),
    adjunto NUMBER (9,0),
    estado NUMBER (9,0),
    tipo NUMBER (9,0),
    motivo NUMBER (9,0),
    CONSTRAINT PERMISO_PK PRIMARY KEY (id_permiso),
    CONSTRAINT PERMISO_FK_USUARIO FOREIGN KEY (usuario) REFERENCES USUARIOS (rut),
    CONSTRAINT PERMISO_FK_RESOLUCION FOREIGN KEY (resolucion) REFERENCES PERMISO_RESOLUCIONES (id_resolucion),
    CONSTRAINT PERMISO_FK_ADJUNTO FOREIGN KEY (adjunto) REFERENCES PERMISO_ADJUNTOS (id_adjunto),
    CONSTRAINT PERMISO_FK_MOTIVO FOREIGN KEY (motivo) REFERENCES PERMISO_MOTIVOS (id_motivo),
    CONSTRAINT PERMISO_FK_TIPO FOREIGN KEY (tipo) REFERENCES PERMISO_TIPOS (id_tipo),
    CONSTRAINT PERMISO_FK_ESTADO FOREIGN KEY (estado) REFERENCES PERMISO_ESTADOS (id_estado)
);

--	CREACIÓN DE SECUENCIAS	--

CREATE SEQUENCE SEQ_PERMISOS INCREMENT BY 1 START WITH 100 MAXVALUE 999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SEQ_PERMISO_ADJUNTOS INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE SEQ_PERMISO_ESTADOS INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE SEQ_PERMISO_MOTIVOS INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE SEQ_PERMISO_RESOLUCIONES INCREMENT BY 1 START WITH 10000 MAXVALUE 999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE SEQ_PERMISO_TIPOS INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SEQ_USUARIO_CARGOS INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE SEQ_USUARIO_DEPARTAMENTOS INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE SEQ_USUARIO_PERFILES INCREMENT BY 1 START WITH 1 MAXVALUE 999999999 MINVALUE 1 CACHE 20;

CREATE SEQUENCE SEQ_FERIADOS INCREMENT BY 1 MAXVALUE 9999999999 MINVALUE 1 CACHE 20;

COMMIT;