-- 	INGRESO DE DATOS DE LA TABLA USUARIO_DEPARTAMENTOS	--

INSERT INTO USUARIO_DEPARTAMENTOS (ID_DEPARTAMENTO, DEPARTAMENTO, DESCRIPCION) VALUES (SEQ_USUARIO_DEPARTAMENTOS.NEXTVAL, 'DIRECCION GENERAL', 'Descripcion del departamento Direccion General');
INSERT INTO USUARIO_DEPARTAMENTOS (ID_DEPARTAMENTO, DEPARTAMENTO, DESCRIPCION) VALUES (SEQ_USUARIO_DEPARTAMENTOS.NEXTVAL, 'RECURSOS HUMANOS', 'Descripcion del departamento Recursos Humanos');
INSERT INTO USUARIO_DEPARTAMENTOS (ID_DEPARTAMENTO, DEPARTAMENTO, DESCRIPCION) VALUES (SEQ_USUARIO_DEPARTAMENTOS.NEXTVAL, 'FINANZAS Y CONTABILIDAD', 'Descripcion del departamento Finanzas y Contabilidad');
INSERT INTO USUARIO_DEPARTAMENTOS (ID_DEPARTAMENTO, DEPARTAMENTO, DESCRIPCION) VALUES (SEQ_USUARIO_DEPARTAMENTOS.NEXTVAL, 'INFORMATICA', 'Descripcion del departamento Informatica');

-- 	INGRESO DE DATOS DE LA TABLA USUARIO_CARGOS	--
INSERT INTO USUARIO_CARGOS (ID_CARGO, CARGO, DESCRIPCION) VALUES (SEQ_USUARIO_CARGOS.NEXTVAL, 'DIRECTOR EJECUTIVO', 'Descripcion del cargo Director Ejecutivo');
INSERT INTO USUARIO_CARGOS (ID_CARGO, CARGO, DESCRIPCION) VALUES (SEQ_USUARIO_CARGOS.NEXTVAL, 'DIRECTOR DE OPERACIONES', 'Descripcion del cargo Director de Operaciones');
INSERT INTO USUARIO_CARGOS (ID_CARGO, CARGO, DESCRIPCION) VALUES (SEQ_USUARIO_CARGOS.NEXTVAL, 'DIRECTOR COMERCIAL', 'Descripcion del cargo Director Comercial');
INSERT INTO USUARIO_CARGOS (ID_CARGO, CARGO, DESCRIPCION) VALUES (SEQ_USUARIO_CARGOS.NEXTVAL, 'DIRECTOR DE RECURSOS HUMANOS', 'Descripcion del cargo Director de Recursos Humanos');
INSERT INTO USUARIO_CARGOS (ID_CARGO, CARGO, DESCRIPCION) VALUES (SEQ_USUARIO_CARGOS.NEXTVAL, 'PROGRAMADOR', 'Descripcion del cargo Programador');

-- 	INGRESO DE DATOS DE LA TABLA PERMISO_ESTADOS	--
INSERT INTO PERMISO_ESTADOS (ID_ESTADO, ESTADO, DESCRIPCION) VALUES (SEQ_PERMISO_ESTADOS.NEXTVAL, 'EMITIDO', 'Descripcion del estado del permiso Emitido');
INSERT INTO PERMISO_ESTADOS (ID_ESTADO, ESTADO, DESCRIPCION) VALUES (SEQ_PERMISO_ESTADOS.NEXTVAL, 'APROBADO', 'Descripcion del estado del permiso Aprobado');
INSERT INTO PERMISO_ESTADOS (ID_ESTADO, ESTADO, DESCRIPCION) VALUES (SEQ_PERMISO_ESTADOS.NEXTVAL, 'RECHAZADO', 'Descripcion del estado del permiso Rechazado');
INSERT INTO PERMISO_ESTADOS (ID_ESTADO, ESTADO, DESCRIPCION) VALUES (SEQ_PERMISO_ESTADOS.NEXTVAL, 'DESISTIDO', 'Descripcion del estado del permiso Desistido');

-- 	INGRESO DE DATOS DE LA TABLA PERMISO_TIPO	--
INSERT INTO PERMISO_TIPOS (ID_TIPO, TIPO, DESCRIPCION, ESTADO_TIPO) VALUES (SEQ_PERMISO_TIPOS.NEXTVAL, 'ADMINISTRATIVO', 'Permiso Administrativo', 1);
INSERT INTO PERMISO_TIPOS (ID_TIPO, TIPO, DESCRIPCION, ESTADO_TIPO) VALUES (SEQ_PERMISO_TIPOS.NEXTVAL, 'FALLECIMIENTO', 'Permiso por Fallecimiento de Familiar Directo', 1) ;
INSERT INTO PERMISO_TIPOS (ID_TIPO, TIPO, DESCRIPCION, ESTADO_TIPO) VALUES (SEQ_PERMISO_TIPOS.NEXTVAL, 'LEGAL', 'Permiso Legal Anual', 1) ;
INSERT INTO PERMISO_TIPOS (ID_TIPO, TIPO, DESCRIPCION, ESTADO_TIPO) VALUES (SEQ_PERMISO_TIPOS.NEXTVAL, 'PARENTAL', 'Permiso Parental', 1) ;

-- 	INGRESO DE DATOS DE LA TABLA USUARIO_PERFIL	--
INSERT INTO USUARIO_PERFILES (ID_PERFIL, PERFIL, DESCRIPCION) VALUES (SEQ_USUARIO_PERFILES.NEXTVAL, 'ADMINISTRADOR', 'Descripcion del perfil Administrador') ;
INSERT INTO USUARIO_PERFILES (ID_PERFIL, PERFIL, DESCRIPCION) VALUES (SEQ_USUARIO_PERFILES.NEXTVAL, 'FUNCIONARIO', 'Descripcion del perfil Funcionario') ;
INSERT INTO USUARIO_PERFILES (ID_PERFIL, PERFIL, DESCRIPCION) VALUES (SEQ_USUARIO_PERFILES.NEXTVAL, 'JEFE INTERNO', 'Descripcion del perfil Jefe Interno') ;
INSERT INTO USUARIO_PERFILES (ID_PERFIL, PERFIL, DESCRIPCION) VALUES (SEQ_USUARIO_PERFILES.NEXTVAL, 'JEFE SUPERIOR', 'Descripcion del perfil Jefe Superior') ;
INSERT INTO USUARIO_PERFILES (ID_PERFIL, PERFIL, DESCRIPCION) VALUES (SEQ_USUARIO_PERFILES.NEXTVAL, 'ALCALDE', 'Descripcion del perfil Alcalde') ;

-- 	INGRESO DE DATOS DE LA TABLA USUARIO	--
INSERT INTO USUARIOS (RUT, DV, CLAVE, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, PERFIL)
VALUES (11111111,'1', 'administrador', 'Administrador', 'Ap_Paterno', 'Ap_Materno', 1);

INSERT INTO USUARIOS (RUT, DV, CLAVE, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, PERFIL, CARGO, DEPARTAMENTO, DIRECCION, COMUNA, TELEFONO, EMAIL, DD_LEGALES, DD_ADMINISTRATIVOS, FECHA_CONTRATO)
VALUES (22222222,'2', 'funcionario', 'Funcionario 2', 'Ap_Paterno', 'Ap_Materno', 2, 5, 4, 'CALLE UNO 1','SANTIAGO CENTRO', 911111111, 'FERNANDO.CHATA@GMAIL.COM', 100, 100, TO_DATE('31-12-2010' ,'DD-MM-YYYY'));

INSERT INTO USUARIOS (RUT, DV, CLAVE, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, PERFIL, CARGO, DEPARTAMENTO, DIRECCION, COMUNA, TELEFONO, EMAIL, DD_LEGALES, DD_ADMINISTRATIVOS, FECHA_CONTRATO)
VALUES (22222221,'1', 'funcionario', 'Funcionario 1', 'Ap_Paterno', 'Ap_Materno', 2, 5, 4, 'CALLE DOS 2','LA CISTERNA', 922222222, 'JOAN.GONZALES@GMAIL.COM', 50, 50, TO_DATE('28-02-2017' ,'DD-MM-YYYY'));

INSERT INTO USUARIOS (RUT, DV, CLAVE, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, PERFIL, CARGO, DEPARTAMENTO, DIRECCION, COMUNA, TELEFONO, EMAIL, DD_LEGALES, DD_ADMINISTRATIVOS, FECHA_CONTRATO)
VALUES (22222223,'3', 'funcionario', 'Funcionario 3', 'Ap_Paterno', 'Ap_Materno', 2, 5, 4, 'CALLE TRES 3','LAS CONDES', 933333333, 'CORREO@GMAIL.COM', 25, 25, TO_DATE('01-01-2018' ,'DD-MM-YYYY'));

INSERT INTO USUARIOS (RUT, DV, CLAVE, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, PERFIL, CARGO, DEPARTAMENTO)
VALUES (33333333,'3', 'interno', 'Jefe Interno', 'Ap_Paterno', 'Ap_Materno', 3, 3, 4);

INSERT INTO USUARIOS (RUT, DV, CLAVE, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, PERFIL, CARGO, DEPARTAMENTO)
VALUES (44444444,'4', 'superior', 'Jefe Superior', 'Ap_Paterno', 'Ap_Materno', 4, 2, 4);

INSERT INTO USUARIOS (RUT, DV, CLAVE, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, PERFIL)
VALUES (55555555,'5', 'alcalde', 'Alcalde', 'Ap_Paterno', 'Ap_Materno', 5);


INSERT INTO USUARIOS (RUT, DV, CLAVE, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, PERFIL, CARGO, DEPARTAMENTO, DIRECCION, COMUNA, TELEFONO, EMAIL, DD_LEGALES, DD_ADMINISTRATIVOS, FECHA_CONTRATO)
VALUES (22042308,'5', 'fernando','Fernando Elias', 'Chata', 'LLamoca', 2, 5, 4, 'LO ENCALADA 1212 DEPTO 8', 'LA CISTERNA', 955204936, 'FERNANDO.CHATA@GMAIL.COM', 50, 100, TO_DATE('30-12-2000' ,'DD-MM-YYYY'));


INSERT INTO USUARIOS (RUT, DV, CLAVE, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, PERFIL, CARGO, DEPARTAMENTO, DIRECCION, COMUNA, TELEFONO, EMAIL, DD_LEGALES, DD_ADMINISTRATIVOS, FECHA_CONTRATO)
VALUES (15932623, '3', 'joan','Joan Manuel', 'Toro', 'Ortiz', 2, 5, 4, 'CALLE ESCONDIDA 456', 'LAS CONDES', 999999999, 'JOAN.TORO@GMAIL.COM', 6, 12, TO_DATE('10-02-2010', 'DD-MM-YYYY')); 


-- 	INGRESO DE DATOS DE LA TABLA PERMISO_MOTIVOS	--
INSERT INTO PERMISO_MOTIVOS (ID_MOTIVO, MOTIVO) VALUES (SEQ_PERMISO_MOTIVOS.NEXTVAL, 'VIAJE FAMILIAR');
INSERT INTO PERMISO_MOTIVOS (ID_MOTIVO, MOTIVO) VALUES (SEQ_PERMISO_MOTIVOS.NEXTVAL, 'MOTIVOS PERSONALES 2');
INSERT INTO PERMISO_MOTIVOS (ID_MOTIVO, MOTIVO) VALUES (SEQ_PERMISO_MOTIVOS.NEXTVAL, 'MOTIVOS PERSONALES 3');
INSERT INTO PERMISO_MOTIVOS (ID_MOTIVO, MOTIVO) VALUES (SEQ_PERMISO_MOTIVOS.NEXTVAL, 'MOTIVOS PERSONALES 4');
INSERT INTO PERMISO_MOTIVOS (ID_MOTIVO, MOTIVO) VALUES (SEQ_PERMISO_MOTIVOS.NEXTVAL, 'MOTIVOS PERSONALES 5');
INSERT INTO PERMISO_MOTIVOS (ID_MOTIVO, MOTIVO) VALUES (SEQ_PERMISO_MOTIVOS.NEXTVAL, 'MOTIVOS PERSONALES 6');
INSERT INTO PERMISO_MOTIVOS (ID_MOTIVO, MOTIVO) VALUES (SEQ_PERMISO_MOTIVOS.NEXTVAL, 'MOTIVOS PERSONALES 7');
INSERT INTO PERMISO_MOTIVOS (ID_MOTIVO, MOTIVO) VALUES (SEQ_PERMISO_MOTIVOS.NEXTVAL, 'MOTIVOS PERSONALES 8');
INSERT INTO PERMISO_MOTIVOS (ID_MOTIVO, MOTIVO) VALUES (SEQ_PERMISO_MOTIVOS.NEXTVAL, 'MOTIVOS PERSONALES 9');


-- 	INGRESO DE DATOS DE LA TABLA PERMISOS	--
INSERT INTO PERMISOS (ID_PERMISO, FECHA_CREACION, FECHA_DESDE, FECHA_HASTA, DIAS, USUARIO, ESTADO, TIPO, MOTIVO)
VALUES (SEQ_PERMISOS.NEXTVAL, TO_DATE('15-03-2018' ,'DD-MM-YYYY'), TO_DATE('25-03-2018' ,'DD-MM-YYYY'), TO_DATE('02-04-2018' ,'DD-MM-YYYY'), 5, 22042308, 2, 3, 1);

INSERT INTO PERMISOS (ID_PERMISO, FECHA_CREACION, FECHA_DESDE, FECHA_HASTA, DIAS, USUARIO, ESTADO, TIPO, MOTIVO)
VALUES (SEQ_PERMISOS.NEXTVAL, TO_DATE('10-01-2018' ,'DD-MM-YYYY'), TO_DATE('15-01-2018' ,'DD-MM-YYYY'), TO_DATE('25-01-2018' ,'DD-MM-YYYY'), 5, 22222222, 2, 3, 2);

INSERT INTO PERMISOS (ID_PERMISO, FECHA_CREACION, FECHA_DESDE, FECHA_HASTA, DIAS, USUARIO, ESTADO, TIPO, MOTIVO)
VALUES (SEQ_PERMISOS.NEXTVAL, TO_DATE('10-02-2018' ,'DD-MM-YYYY'), TO_DATE('15-02-2018' ,'DD-MM-YYYY'), TO_DATE('25-02-2018' ,'DD-MM-YYYY'), 5, 22222222, 2, 1, 3);

INSERT INTO PERMISOS (ID_PERMISO, FECHA_CREACION, FECHA_DESDE, FECHA_HASTA, DIAS, USUARIO, ESTADO, TIPO, MOTIVO)
VALUES (SEQ_PERMISOS.NEXTVAL, TO_DATE('10-01-2018' ,'DD-MM-YYYY'), TO_DATE('15-01-2018' ,'DD-MM-YYYY'), TO_DATE('25-01-2018' ,'DD-MM-YYYY'), 5, 22222221, 1, 1, 4);

INSERT INTO PERMISOS (ID_PERMISO, FECHA_CREACION, FECHA_DESDE, FECHA_HASTA, DIAS, USUARIO, ESTADO, TIPO, MOTIVO)
VALUES (SEQ_PERMISOS.NEXTVAL, TO_DATE('10-02-2018' ,'DD-MM-YYYY'), TO_DATE('15-02-2018' ,'DD-MM-YYYY'), TO_DATE('25-02-2018' ,'DD-MM-YYYY'), 5, 22222223, 3, 1, 5);

INSERT INTO PERMISOS (ID_PERMISO, FECHA_CREACION, FECHA_DESDE, FECHA_HASTA, DIAS, USUARIO, ESTADO, TIPO, MOTIVO)
VALUES (SEQ_PERMISOS.NEXTVAL, TO_DATE('10-03-2018' ,'DD-MM-YYYY'), TO_DATE('15-03-2018' ,'DD-MM-YYYY'), TO_DATE('25-03-2018' ,'DD-MM-YYYY'), 5, 22222223, 3, 1, 6);

INSERT INTO PERMISOS (ID_PERMISO, FECHA_CREACION, FECHA_DESDE, FECHA_HASTA, DIAS, USUARIO, ESTADO, TIPO, MOTIVO)
VALUES (SEQ_PERMISOS.NEXTVAL, TO_DATE('10-01-2018' ,'DD-MM-YYYY'), TO_DATE('15-01-2018' ,'DD-MM-YYYY'), TO_DATE('25-01-2018' ,'DD-MM-YYYY'), 5, 22222223, 3, 1, 7);

INSERT INTO PERMISOS (ID_PERMISO, FECHA_CREACION, FECHA_DESDE, FECHA_HASTA, DIAS, USUARIO, ESTADO, TIPO, MOTIVO)
VALUES (SEQ_PERMISOS.NEXTVAL, TO_DATE('10-02-2018' ,'DD-MM-YYYY'), TO_DATE('15-02-2018' ,'DD-MM-YYYY'), TO_DATE('25-02-2018' ,'DD-MM-YYYY'), 5, 22222221, 1, 1, 8);

INSERT INTO PERMISOS (ID_PERMISO, FECHA_CREACION, FECHA_DESDE, FECHA_HASTA, DIAS, USUARIO, ESTADO, TIPO, MOTIVO)
VALUES (SEQ_PERMISOS.NEXTVAL, TO_DATE('10-03-2018' ,'DD-MM-YYYY'), TO_DATE('15-03-2018' ,'DD-MM-YYYY'), TO_DATE('25-03-2018' ,'DD-MM-YYYY'), 5, 22222222, 2, 1, 9);


INSERT INTO PERMISO_ADJUNTOS (ID_ADJUNTO) VALUES (0);

INSERT INTO PERMISO_RESOLUCIONES (ID_RESOLUCION) VALUES (0);

-- 	INGRESO DE DATOS DE LA TABLA FERIADOS	--
--	2018
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('01-01-2018' ,'DD-MM-YYYY'), 'Año Nuevo-Irrenunciable-Civil, Ley 2.977-Ley 19.973');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('30-03-2018' ,'DD-MM-YYYY'), 'Viernes Santo-Religioso, Ley 2.977');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('31-03-2018' ,'DD-MM-YYYY'), 'Sábado Santo-Religioso, Ley 2.977');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('01-05-2018' ,'DD-MM-YYYY'), 'Día Nacional del Trabajo-Irrenunciable-Civil, Ley 19.973');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('21-05-2018' ,'DD-MM-YYYY'), 'Día de las Glorias Navales-Civil, Ley 2.977');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('02-07-2018' ,'DD-MM-YYYY'), 'San Pedro y San Pablo-Religioso, Ley 2.977-Ley 18.432-Ley 19.668');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('16-07-2018' ,'DD-MM-YYYY'), 'Día de la Virgen del Carmen-Religioso, Ley 20.148');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('15-08-2018' ,'DD-MM-YYYY'), 'Asunción de la Virgen-Religioso, Ley 2.977');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('17-09-2018' ,'DD-MM-YYYY'), 'Fiestas Patrias-Civil, Ley 20.215');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('18-09-2018' ,'DD-MM-YYYY'), 'Independencia Nacional-Irrenunciable-Civil, Ley 2.977-Ley 19.973');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('19-09-2018' ,'DD-MM-YYYY'), 'Día de las Glorias del Ejército-Irrenunciable-Civil, Ley 2.977-Ley 20.629');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('15-10-2018' ,'DD-MM-YYYY'), 'Encuentro de Dos Mundos-Civil, Ley 3.810-Ley 19.668');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('01-11-2018' ,'DD-MM-YYYY'), 'Día de Todos los Santos-Religioso, Ley 2.977');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('02-11-2018' ,'DD-MM-YYYY'), 'Día de las Iglesias Evangélicas y Protestantes-Religioso, Ley 20.299');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('08-12-2018' ,'DD-MM-YYYY'), 'Inmaculada Concepción-Religioso, Ley 2.977');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('25-12-2018' ,'DD-MM-YYYY'), 'Navidad-Irrenunciable-Religioso, Ley 2.977-Ley 19.973');
-- 2019
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('01-01-2019' ,'DD-MM-YYYY'), 'Año Nuevo-Irrenunciable	Civil-Ley 2.977-Ley 19.973');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('19-04-2019' ,'DD-MM-YYYY'), 'Viernes Santo-Religioso-Ley 2.977');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('20-04-2019' ,'DD-MM-YYYY'), 'Santo-Religioso-Ley 2.977');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('01-05-2019' ,'DD-MM-YYYY'), 'Día Nacional del Trabajo-Irrenunciable-Civil-Ley 19.973');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('21-05-2019' ,'DD-MM-YYYY'), 'Día de las Glorias Navales-Civil-Ley 2.977');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('29-06-2019' ,'DD-MM-YYYY'), 'San Pedro y San Pablo-Religioso-Ley 2.977-Ley 18.432-16-07Ley 19.668');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('16-07-2019' ,'DD-MM-YYYY'), 'Día de la Virgen del Carmen	Religioso-Ley 20.148');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('15-09-2019' ,'DD-MM-YYYY'), 'Asunción de la Virgen-Religioso-Ley 2.977');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('18-09-2019' ,'DD-MM-YYYY'), 'Independencia Nacional-Irrenunciable-Civil-Ley 2.977-Ley 19.973');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('19-09-2019' ,'DD-MM-YYYY'), 'Día de las Glorias del Ejército-Irrenunciable-Civil-Ley 2.977-Ley 20.629');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('20-09-2019' ,'DD-MM-YYYY'), 'Fiestas Patrias-Civil-Ley 20.215');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('12-10-2019' ,'DD-MM-YYYY'), 'Encuentro de Dos Mundos-Civil-Ley 3.810-Ley 19.668');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('31-10-2019' ,'DD-MM-YYYY'), 'Día de las Iglesias Evangélicas y Protestantes-Religioso-Ley 20.299');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('01-11-2019' ,'DD-MM-YYYY'), 'Día de Todos los Santos-Religioso-Ley 2.977');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('08-12-2019' ,'DD-MM-YYYY'), 'Inmaculada Concepción-Religioso-Ley 2.977');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (SEQ_FERIADOS.NEXTVAL, TO_DATE('25-12-2019' ,'DD-MM-YYYY'), 'Navidad-Irrenunciable-Religioso-Ley 2.977-Ley 19.973');

COMMIT;