-- 	INGRESO DE DATOS DE LA TABLA USUARIO_DEPARTAMENTOS	--

INSERT INTO USUARIO_DEPARTAMENTOS (ID_DEPARTAMENTO, DEPARTAMENTO, DESCRIPCION) VALUES (SEQ_USUARIO_DEPARTAMENTOS.NEXTVAL, 'DIRECCION GENERAL', 'Descripcion del departamento Direccion General');
INSERT INTO USUARIO_DEPARTAMENTOS (ID_DEPARTAMENTO, DEPARTAMENTO, DESCRIPCION) VALUES (SEQ_USUARIO_DEPARTAMENTOS.NEXTVAL, 'RECURSOS HUMANOS', 'Descripcion del departamento Recursos Humanos');
INSERT INTO USUARIO_DEPARTAMENTOS (ID_DEPARTAMENTO, DEPARTAMENTO, DESCRIPCION) VALUES (SEQ_USUARIO_DEPARTAMENTOS.NEXTVAL, 'FINANZAS Y CONTABILIDAD', 'Descripcion del departamento Finanzas y Contabilidad');
INSERT INTO USUARIO_DEPARTAMENTOS (ID_DEPARTAMENTO, DEPARTAMENTO, DESCRIPCION) VALUES (SEQ_USUARIO_DEPARTAMENTOS.NEXTVAL, 'INFORMATICA', 'Descripcion del departamento Informatica');

-- 	INGRESO DE DATOS DE LA TABLA USUARIO_CARGOS	--
INSERT INTO USUARIO_CARGOS (ID_CARGO, CARGO, DESCRIPCION) VALUES (1, 'DIRECTOR EJECUTIVO', 'Descripcion del cargo Director Ejecutivo');
INSERT INTO USUARIO_CARGOS (ID_CARGO, CARGO, DESCRIPCION) VALUES (2, 'DIRECTOR DE OPERACIONES', 'Descripcion del cargo Director de Operaciones');
INSERT INTO USUARIO_CARGOS (ID_CARGO, CARGO, DESCRIPCION) VALUES (3, 'DIRECTOR COMERCIAL', 'Descripcion del cargo Director Comercial');
INSERT INTO USUARIO_CARGOS (ID_CARGO, CARGO, DESCRIPCION) VALUES (4, 'DIRECTOR DE RECURSOS HUMANOS', 'Descripcion del cargo Director de Recursos Humanos');
INSERT INTO USUARIO_CARGOS (ID_CARGO, CARGO, DESCRIPCION) VALUES (5, 'PROGRAMADOR', 'Descripcion del cargo Programador');

-- 	INGRESO DE DATOS DE LA TABLA PERMISO_ESTADOS	--
INSERT INTO PERMISO_ESTADOS (ID_ESTADO, ESTADO, DESCRIPCION) VALUES (SEQ_PERMISO_ESTADOS.NEXTVAL, 'EMITIDO', 'Descripcion del estado del permiso Emitido');
INSERT INTO PERMISO_ESTADOS (ID_ESTADO, ESTADO, DESCRIPCION) VALUES (SEQ_PERMISO_ESTADOS.NEXTVAL, 'EN PROCESO', 'Descripcion del estado del permiso En Proceso');
INSERT INTO PERMISO_ESTADOS (ID_ESTADO, ESTADO, DESCRIPCION) VALUES (SEQ_PERMISO_ESTADOS.NEXTVAL, 'APROBADO', 'Descripcion del estado del permiso Aprobado');
INSERT INTO PERMISO_ESTADOS (ID_ESTADO, ESTADO, DESCRIPCION) VALUES (SEQ_PERMISO_ESTADOS.NEXTVAL, 'RECHAZADO', 'Descripcion del estado del permiso Rechazado');


-- 	INGRESO DE DATOS DE LA TABLA PERMISO_TIPO	--
INSERT INTO PERMISO_TIPOS (ID_TIPO, TIPO, DIAS, DESCRIPCION, ESTADO_TIPO) VALUES (SEQ_PERMISO_TIPOS.NEXTVAL, 'ADMINISTRATIVO', 0, 'Permiso Administrativo', 1);
INSERT INTO PERMISO_TIPOS (ID_TIPO, TIPO, DIAS, DESCRIPCION, ESTADO_TIPO) VALUES (SEQ_PERMISO_TIPOS.NEXTVAL, 'FALLECIMIENTO', 7, 'Permiso por Fallecimiento de Familiar Directo', 1) ;
INSERT INTO PERMISO_TIPOS (ID_TIPO, TIPO, DIAS, DESCRIPCION, ESTADO_TIPO) VALUES (SEQ_PERMISO_TIPOS.NEXTVAL, 'LEGAL', 0, 'Permiso Legal Anual', 1) ;
INSERT INTO PERMISO_TIPOS (ID_TIPO, TIPO, DIAS, DESCRIPCION, ESTADO_TIPO) VALUES (SEQ_PERMISO_TIPOS.NEXTVAL, 'PARENTAL', 7, 'Permiso Parental', 1) ;


-- 	INGRESO DE DATOS DE LA TABLA FERIADOS	--
--	2018
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (1, TO_DATE('01-01-2018' ,'DD-MM-YYYY'), 'A�o Nuevo-Irrenunciable-Civil, Ley 2.977-Ley 19.973');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (2, TO_DATE('30-03-2018' ,'DD-MM-YYYY'), 'Viernes Santo-Religioso, Ley 2.977');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (3, TO_DATE('31-03-2018' ,'DD-MM-YYYY'), 'S�bado Santo-Religioso, Ley 2.977');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (4, TO_DATE('01-05-2018' ,'DD-MM-YYYY'), 'D�a Nacional del Trabajo-Irrenunciable-Civil, Ley 19.973');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (5, TO_DATE('21-05-2018' ,'DD-MM-YYYY'), 'D�a de las Glorias Navales-Civil, Ley 2.977');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (6, TO_DATE('02-07-2018' ,'DD-MM-YYYY'), 'San Pedro y San Pablo-Religioso, Ley 2.977-Ley 18.432-Ley 19.668');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (7, TO_DATE('16-07-2018' ,'DD-MM-YYYY'), 'D�a de la Virgen del Carmen-Religioso, Ley 20.148');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (8, TO_DATE('15-08-2018' ,'DD-MM-YYYY'), 'Asunci�n de la Virgen-Religioso, Ley 2.977');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (9, TO_DATE('17-09-2018' ,'DD-MM-YYYY'), 'Fiestas Patrias-Civil, Ley 20.215');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (10, TO_DATE('18-09-2018' ,'DD-MM-YYYY'), 'Independencia Nacional-Irrenunciable-Civil, Ley 2.977-Ley 19.973');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (11, TO_DATE('19-09-2018' ,'DD-MM-YYYY'), 'D�a de las Glorias del Ej�rcito-Irrenunciable-Civil, Ley 2.977-Ley 20.629');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (12, TO_DATE('15-10-2018' ,'DD-MM-YYYY'), 'Encuentro de Dos Mundos-Civil, Ley 3.810-Ley 19.668');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (13, TO_DATE('01-11-2018' ,'DD-MM-YYYY'), 'D�a de Todos los Santos-Religioso, Ley 2.977');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (14, TO_DATE('02-11-2018' ,'DD-MM-YYYY'), 'D�a de las Iglesias Evang�licas y Protestantes-Religioso, Ley 20.299');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (15, TO_DATE('08-12-2018' ,'DD-MM-YYYY'), 'Inmaculada Concepci�-Religioso, Ley 2.977');
INSERT INTO FERIADOS (ID_FERIADO, FERIADO, DESCRIPCION) VALUES (16, TO_DATE('25-12-2018' ,'DD-MM-YYYY'), 'Navidad-Irrenunciable-Religioso, Ley 2.977-Ley 19.973');

-- 	INGRESO DE DATOS DE LA TABLA USUARIO_PERFIL	--
INSERT INTO USUARIO_PERFILES (ID_PERFIL, PERFIL, DESCRIPCION) VALUES (SEQ_USUARIO_PERFILES.NEXTVAL, 'ADMINISTRADOR', 'Descripcion del perfil Administrador') ;
INSERT INTO USUARIO_PERFILES (ID_PERFIL, PERFIL, DESCRIPCION) VALUES (SEQ_USUARIO_PERFILES.NEXTVAL, 'FUNCIONARIO', 'Descripcion del perfil Funcionario') ;
INSERT INTO USUARIO_PERFILES (ID_PERFIL, PERFIL, DESCRIPCION) VALUES (SEQ_USUARIO_PERFILES.NEXTVAL, 'JEFE INTERNO', 'Descripcion del perfil Jefe Interno') ;
INSERT INTO USUARIO_PERFILES (ID_PERFIL, PERFIL, DESCRIPCION) VALUES (SEQ_USUARIO_PERFILES.NEXTVAL, 'JEFE SUPERIOR', 'Descripcion del perfil Jefe Superior') ;
INSERT INTO USUARIO_PERFILES (ID_PERFIL, PERFIL, DESCRIPCION) VALUES (SEQ_USUARIO_PERFILES.NEXTVAL, 'ALCALDE', 'Descripcion del perfil Alcalde') ;

-- 	INGRESO DE DATOS DE LA TABLA USUARIO	--
INSERT INTO USUARIOS (RUT, DV, CLAVE, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, PERFIL) VALUES (11111111,'1', 'administrador', 'Administrador', 'Ap_Paterno', 'Ap_Materno', 1);
INSERT INTO USUARIOS (RUT, DV, CLAVE, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, PERFIL, CARGO, DEPARTAMENTO) VALUES (22222222,'2', 'funcionario', 'Funcionario', 'Ap_Paterno', 'Ap_Materno', 2, 5, 4);
INSERT INTO USUARIOS (RUT, DV, CLAVE, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, PERFIL, CARGO, DEPARTAMENTO) VALUES (33333333,'3', 'interno', 'Jefe Interno', 'Ap_Paterno', 'Ap_Materno', 3, 3, 4);
INSERT INTO USUARIOS (RUT, DV, CLAVE, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, PERFIL, CARGO, DEPARTAMENTO) VALUES (44444444,'4', 'superior', 'Jefe Superior', 'Ap_Paterno', 'Ap_Materno', 4, 2, 4);
INSERT INTO USUARIOS (RUT, DV, CLAVE, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, PERFIL) VALUES (55555555,'5', 'alcalde', 'Alcalde', 'Ap_Paterno', 'Ap_Materno', 5);


INSERT INTO USUARIOS (RUT, DV, CLAVE, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, PERFIL, CARGO, DEPARTAMENTO) VALUES (22042308,'5', 'fernando','Fernando Elias', 'Chata', 'LLamoca', 2, 5, 4);
UPDATE USUARIOS SET DIRECCION='LO ENCALADA 1212 DEPTO 8',COMUNA='LA CISTERNA', TELEFONO = 955204936, EMAIL = 'FERNANDO.CHATA@GMAIL.COM', DD_LEGALES = 50, DD_ADMINISTRATIVOS = 100, FECHA_CONTRATO= TO_DATE('30-12-2000' ,'DD-MM-YYYY') WHERE RUT = 22042308;

INSERT INTO USUARIOS (RUT, DV, CLAVE, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, PERFIL) VALUES (15932623, '3', 'joan','Joan Manuel', 'Toro', 'Ortiz', 2);
UPDATE USUARIOS SET DIRECCION='CALLE ESCONDIDA 456',COMUNA='LAS CONDES', TELEFONO = 999999999, EMAIL = 'JOAN.TORO@GMAIL.COM', DD_LEGALES = 3, DD_ADMINISTRATIVOS = 12, FECHA_CONTRATO= TO_DATE('10-02-2010' ,'DD-MM-YYYY'), CARGO = 5, DEPARTAMENTO = 4 WHERE RUT = 15932623;

INSERT INTO USUARIOS (RUT, DV, CLAVE, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, PERFIL) VALUES (10101663, '3', 'jorge','Jorge Luis', 'Gonzales', 'Villafuerte', 2);
UPDATE USUARIOS SET DIRECCION='CALLE FUERTE 234',COMUNA='SANTIAGO CENTRO', TELEFONO = 999999999, EMAIL = 'JOAN.GONZALES@GMAIL.COM', DD_LEGALES = 6, DD_ADMINISTRATIVOS = 5, FECHA_CONTRATO= TO_DATE('10-02-2015' ,'DD-MM-YYYY'), CARGO = 3, DEPARTAMENTO = 2 WHERE RUT = 10101663;



-- 	INGRESO DE DATOS DE LA TABLA PERMISO_MOTIVOS	--
INSERT INTO PERMISO_MOTIVOS (ID_MOTIVO, MOTIVO) VALUES (1, 'VIAJE FAMILIAR');
INSERT INTO PERMISO_MOTIVOS (ID_MOTIVO, MOTIVO) VALUES (2, 'MOTIVOS PERSONALES 2');
INSERT INTO PERMISO_MOTIVOS (ID_MOTIVO, MOTIVO) VALUES (3, 'MOTIVOS PERSONALES 3');
INSERT INTO PERMISO_MOTIVOS (ID_MOTIVO, MOTIVO) VALUES (4, 'MOTIVOS PERSONALES 4');
INSERT INTO PERMISO_MOTIVOS (ID_MOTIVO, MOTIVO) VALUES (5, 'MOTIVOS PERSONALES 5');
INSERT INTO PERMISO_MOTIVOS (ID_MOTIVO, MOTIVO) VALUES (6, 'MOTIVOS PERSONALES 6');
INSERT INTO PERMISO_MOTIVOS (ID_MOTIVO, MOTIVO) VALUES (7, 'MOTIVOS PERSONALES 7');
INSERT INTO PERMISO_MOTIVOS (ID_MOTIVO, MOTIVO) VALUES (8, 'MOTIVOS PERSONALES 8');
INSERT INTO PERMISO_MOTIVOS (ID_MOTIVO, MOTIVO) VALUES (9, 'MOTIVOS PERSONALES 9');


-- 	INGRESO DE DATOS DE LA TABLA PERMISOS	--
INSERT INTO PERMISOS (ID_PERMISO, FECHA_CREACION, FECHA_DESDE, FECHA_HASTA, DIAS, USUARIO, ESTADO, TIPO, MOTIVO) VALUES (1, TO_DATE('15-03-2018' ,'DD-MM-YYYY'), TO_DATE('25-03-2018' ,'DD-MM-YYYY'), TO_DATE('02-04-2018' ,'DD-MM-YYYY'), 5, 22042308, 2, 3, 1);
INSERT INTO PERMISOS (ID_PERMISO) VALUES (2);
UPDATE PERMISOS SET FECHA_CREACION = TO_DATE('10-01-2018' ,'DD-MM-YYYY'), FECHA_DESDE= TO_DATE('15-01-2018' ,'DD-MM-YYYY'), FECHA_HASTA= TO_DATE('25-01-2018' ,'DD-MM-YYYY'), DIAS= 5, USUARIO= 22042308, ESTADO= 3, TIPO= 3, MOTIVO= 2 WHERE ID_PERMISO =2;
INSERT INTO PERMISOS (ID_PERMISO) VALUES (3);
UPDATE PERMISOS SET FECHA_CREACION = TO_DATE('10-02-2018' ,'DD-MM-YYYY'), FECHA_DESDE= TO_DATE('15-02-2018' ,'DD-MM-YYYY'), FECHA_HASTA= TO_DATE('25-02-2018' ,'DD-MM-YYYY'), DIAS= 5, USUARIO= 22042308, ESTADO= 3, TIPO= 1, MOTIVO= 3 WHERE ID_PERMISO =3;
INSERT INTO PERMISOS (ID_PERMISO) VALUES (4);
UPDATE PERMISOS SET FECHA_CREACION = TO_DATE('10-01-2018' ,'DD-MM-YYYY'), FECHA_DESDE= TO_DATE('15-01-2018' ,'DD-MM-YYYY'), FECHA_HASTA= TO_DATE('25-01-2018' ,'DD-MM-YYYY'), DIAS= 5, USUARIO= 15932623, ESTADO= 3, TIPO= 1, MOTIVO= 4 WHERE ID_PERMISO =4;
INSERT INTO PERMISOS (ID_PERMISO) VALUES (5);
UPDATE PERMISOS SET FECHA_CREACION = TO_DATE('10-02-2018' ,'DD-MM-YYYY'), FECHA_DESDE= TO_DATE('15-02-2018' ,'DD-MM-YYYY'), FECHA_HASTA= TO_DATE('25-02-2018' ,'DD-MM-YYYY'), DIAS= 5, USUARIO= 15932623, ESTADO= 3, TIPO= 1, MOTIVO= 5 WHERE ID_PERMISO =5;
INSERT INTO PERMISOS (ID_PERMISO) VALUES (6);
UPDATE PERMISOS SET FECHA_CREACION = TO_DATE('10-03-2018' ,'DD-MM-YYYY'), FECHA_DESDE= TO_DATE('15-03-2018' ,'DD-MM-YYYY'), FECHA_HASTA= TO_DATE('25-03-2018' ,'DD-MM-YYYY'), DIAS= 5, USUARIO= 15932623, ESTADO= 3, TIPO= 1, MOTIVO= 6 WHERE ID_PERMISO =6;
INSERT INTO PERMISOS (ID_PERMISO) VALUES (7);
UPDATE PERMISOS SET FECHA_CREACION = TO_DATE('10-01-2018' ,'DD-MM-YYYY'), FECHA_DESDE= TO_DATE('15-01-2018' ,'DD-MM-YYYY'), FECHA_HASTA= TO_DATE('25-01-2018' ,'DD-MM-YYYY'), DIAS= 5, USUARIO= 10101663, ESTADO= 3, TIPO= 1, MOTIVO= 7 WHERE ID_PERMISO =7;
INSERT INTO PERMISOS (ID_PERMISO) VALUES (8);
UPDATE PERMISOS SET FECHA_CREACION = TO_DATE('10-02-2018' ,'DD-MM-YYYY'), FECHA_DESDE= TO_DATE('15-02-2018' ,'DD-MM-YYYY'), FECHA_HASTA= TO_DATE('25-02-2018' ,'DD-MM-YYYY'), DIAS= 5, USUARIO= 10101663, ESTADO= 3, TIPO= 1, MOTIVO= 8 WHERE ID_PERMISO =8;
INSERT INTO PERMISOS (ID_PERMISO) VALUES (9);
UPDATE PERMISOS SET FECHA_CREACION = TO_DATE('10-03-2018' ,'DD-MM-YYYY'), FECHA_DESDE= TO_DATE('15-03-2018' ,'DD-MM-YYYY'), FECHA_HASTA= TO_DATE('25-03-2018' ,'DD-MM-YYYY'), DIAS= 5, USUARIO= 10101663, ESTADO= 3, TIPO= 1, MOTIVO= 9 WHERE ID_PERMISO =9;


INSERT INTO PERMISO_ADJUNTOS (ID_ADJUNTO) VALUES (0);

INSERT INTO PERMISO_RESOLUCIONES (ID_RESOLUCION) VALUES (0);

COMMIT;